server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "configserver:"  # ✅ Correct way

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/parking-service/**
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring.security.user:
  name: none
  password: none

jwt:
  secret: 39f0aea7-ff2e-4001-9dd8-ea981a9ee6bf
