server:
  port: 8093
  servlet:
    context-path: /parking-service

spring:
  application:
    name: parking-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/